export const AddRoom_Fields = [
  {
    id: "012",
    name: "owner",
    label: "Owner name",
    type: "text",
    placeholder: "Owner name",
  },
  {
    id: "001",
    name: "title",
    label: "Room Title (Enter your property name)",
    type: "text",
    placeholder: "Enter room title (e.g., Cozy Apartment)",
  },
  {
    id: "002",
    name: "location",
    label: "Location",
    type: "text",
    placeholder: "Enter location (e.g., Rajpur Road, Dehradun)",
  },
  {
    id: "003",
    name: "price",
    label: "Price (₹)",
    type: "number",
    placeholder: "Enter monthly rent",
  },
  {
    id: "004",
    name: "beds",
    label: "Beds",
    type: "text",
    placeholder: "Number of beds",
  },
  {
    id: "005",
    name: "baths",
    label: "Baths",
    type: "text",
    placeholder: "Number of bathrooms",
  },
  {
    id: "006",
    name: "roomType",
    label: "Room Type",
    type: "text",
    placeholder: "Boys PG / Girls PG / Flat",
  },
  {
    id: "007",
    name: "amenities",
    label: "Facilities",
    type: "text",
    placeholder: "Wifi, Parking, Garden (comma separated)",
  },
  {
    id: "008",
    name: "description",
    label: "Room Description",
    type: "textarea",
    placeholder: "Enter room details...",
  },
  {
    id: "009",
    name: "ownerDemands",
    label: "Owner Requirements",
    type: "text",
    placeholder: "Security, no smoking, etc.",
  },
  {
    id: "010",
    name: "contact",
    label: "Contact Number",
    type: "text",
    placeholder: "Enter owner's contact number",
  },
  {
    id: 100,
    name: "images",
    label: "Upload Images",
    type: "file",
  },
];

export const EDIT_FIELDS = [
  { name: "title", label: "Room Title", placeholder: "Room Title" },
  { name: "location", label: "Location", placeholder: "Location" },
  { name: "price", label: "Price", placeholder: "Price" },
  { name: "roomType", label: "Room Type", placeholder: "Room Type" },
  { name: "contact", label: "Contact Number", placeholder: "Contact Number" },
  { name: "beds", label: "Bed's Number", placeholder: "Bed's Number" },
  {
    name: "baths",
    label: "Bathroom's Number",
    placeholder: "Bathroom's Number",
  },
];
