import IMAGES from "@/app/assets/images.constant";
import ROOMS from "@/app/assets/rooms.constant";

export const properties = [
  {
    id: 1,
    title: "Cozy Downtown Apartment",
    location: "Rajpur Road, Dehradun",
    price: 15000,
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Garden"],
    image: ROOMS.room1,
    host: { name: "Aarav Sharma", avatar: IMAGES.hostIcon },
    roomType: "Boy's PG",
    description:
      "A cozy apartment on Rajpur Road, ideal for students or working boys who want quick access to markets and cafes.",
    ownerDemands: "One month advance rent, no late-night parties allowed.",
    contact: "+91 9876543210",
    list: "true",
  },
  {
    id: 2,
    title: "Modern Loft with City View",
    location: "Clock Tower, Dehradun",
    price: 20000,
    beds: 2,
    baths: 2,
    amenities: ["Wifi", "Parking"],
    image: ROOMS.room2,
    host: { name: "Neha Gupta", avatar: IMAGES.hostIcon },
    roomType: "Girl's PG",
    description:
      "Spacious loft near Clock Tower with modern interiors and great city views, perfect for female students or professionals.",
    ownerDemands: "Only vegetarian food allowed, security deposit required.",
    contact: "+91 9123456780",
    list: "false",
  },
  {
    id: 3,
    title: "Hill View Villa",
    location: "Mussoorie Road, Dehradun",
    price: 35000,
    beds: 3,
    baths: 2,
    amenities: ["Wifi", "Pool", "AC"],
    image: ROOMS.room3,
    host: { name: "Rohit Verma", avatar: IMAGES.hostIcon },
    roomType: "Independent Room",
    description:
      "Beautiful villa with scenic Mussoorie hills view, suitable for families or group stays.",
    ownerDemands: "No pets allowed, 2 months advance rent required.",
    contact: "+91 9988776655",
    list: "false",
  },
  {
    id: 4,
    title: "Rustic Mountain Cabin",
    location: "Maldevta, Dehradun",
    price: 18000,
    beds: 2,
    baths: 1,
    amenities: ["Fireplace", "Wifi"],
    image: ROOMS.room4,
    host: { name: "Priya Singh", avatar: IMAGES.hostIcon },
    roomType: "Independent With Food",
    description:
      "Quiet cabin near Maldevta, surrounded by greenery, meals provided by the owner.",
    ownerDemands: "Non-smokers only, 6 months minimum stay.",
    contact: "+91 9001122334",
    list: "false",
  },
  {
    id: 5,
    title: "Luxury Penthouse Suite",
    location: "Sahastradhara Road, Dehradun",
    price: 50000,
    beds: 4,
    baths: 3,
    amenities: ["Wifi", "Gym", "Concierge"],
    image: ROOMS.room5,
    host: { name: "Aditya Mehra", avatar: IMAGES.hostIcon },
    roomType: "Sharing Room",
    description:
      "Premium penthouse on Sahastradhara Road with luxury facilities and gym access.",
    ownerDemands: "Corporate professionals preferred, high maintenance fees.",
    contact: "+91 9765432100",
    list: "false",
  },
  {
    id: 6,
    title: "Charming Countryside Home",
    location: "Doiwala, Dehradun",
    price: 12000,
    beds: 2,
    baths: 1,
    amenities: ["Garden", "Wifi"],
    image: ROOMS.room6,
    host: { name: "Kavya Iyer", avatar: IMAGES.hostIcon },
    roomType: "Boy's PG",
    description:
      "Affordable countryside home in Doiwala, perfect for students seeking peace and greenery.",
    ownerDemands: "Electricity bill extra, no guests allowed after 9 PM.",
    contact: "+91 9098765432",
    list: "true",
  },
  {
    id: 7,
    title: "Studio Near Forest",
    location: "Kandoli, Dehradun",
    price: 10090,
    beds: 1,
    baths: 1,
    amenities: ["Wifi", "Pet Friendly"],
    image: ROOMS.room7,
    host: { name: "Manish Tiwari", avatar: IMAGES.hostIcon },
    roomType: "Girl's PG",
    description:
      "Compact studio near Kandoli forest, peaceful environment with natural surroundings.",
    ownerDemands: "Small pets allowed, but no loud music.",
    contact: "+91 9812345678",
    list: "true",
  },
  {
    id: 8,
    title: "Historic Townhouse",
    location: "Paltan Bazaar, Dehradun",
    price: 22000,
    beds: 3,
    baths: 2,
    amenities: ["Wifi", "Parking"],
    image: ROOMS.room8,
    host: { name: "Sneha Kapoor", avatar: IMAGES.hostIcon },
    roomType: "Independent Room",
    description:
      "Traditional townhouse located in Paltan Bazaar, close to local markets and transport.",
    ownerDemands: "Vegetarian tenants preferred, 1 year lease required.",
    contact: "+91 9876501234",
    list: "true",
  },
  {
    id: 9,
    title: "Quiet Riverside Retreat",
    location: "Rispana, Dehradun",
    price: 14000,
    beds: 2,
    baths: 1,
    amenities: ["AC", "Wifi"],
    image: ROOMS.room9,
    host: { name: "Arjun Nair", avatar: IMAGES.hostIcon },
    roomType: "Independent With Food",
    description:
      "Riverside home in Rispana, peaceful living with daily meals included.",
    ownerDemands: "Advance payment for meals, no alcohol allowed.",
    contact: "+91 9876549876",
    list: "false",
  },
  {
    id: 10,
    title: "Mountain View Chalet",
    location: "Kalsi, Dehradun",
    price: 28000,
    beds: 3,
    baths: 2,
    amenities: ["Fireplace", "Wifi", "Parking"],
    image: ROOMS.room10,
    host: { name: "Ritika Joshi", avatar: IMAGES.hostIcon },
    roomType: "Sharing Room",
    description:
      "Spacious chalet in Kalsi with breathtaking mountain views and fireplace.",
    ownerDemands: "Bachelors not allowed, families preferred.",
    contact: "+91 9988001122",
    list: "false",
  },
  {
    id: 11,
    title: "Sunny Hillside Apartment",
    location: "Rajpur Road, Dehradun",
    price: 18000,
    beds: 2,
    baths: 2,
    amenities: ["Wifi", "Balcony", "AC"],
    image: ROOMS.room11,
    host: { name: "Varun Malhotra", avatar: IMAGES.hostIcon },
    roomType: "Boy's PG",
    description:
      "Bright hillside apartment on Rajpur Road with balcony and modern amenities.",
    ownerDemands: "Security deposit required, non-smokers preferred.",
    contact: "+91 9123098765",
    list: "true",
  },
  {
    id: 12,
    title: "Cozy Garden Cottage",
    location: "Maldevta, Dehradun",
    price: 16000,
    beds: 1,
    baths: 1,
    amenities: ["Garden", "Wifi", "Parking"],
    image: ROOMS.room12,
    host: { name: "Ishita Bansal", avatar: IMAGES.hostIcon },
    roomType: "Girl's PG",
    description:
      "Charming garden cottage in Maldevta, surrounded by nature and fresh air.",
    ownerDemands: "No non-veg cooking inside, 6 months advance preferred.",
    contact: "+91 9011223344",
    list: "true",
  },
];
