import "@/components/custom/typography";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import { Toaster } from "../components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} ${inter.className}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster richColors expand />
      </body>
    </html>
  );
}
